export const CloudConfig = {
	// Movement and animation constants
	VELOCITY_FACTOR: 0.25,
	TARGET_VELOCITY_FACTOR: 0.4,
	MOVEMENT_SPEED: 0.15,
	EASING_FACTOR: 0.02,
	EASING_DIVISOR: 800,
	MIN_DIRECTION_CHANGE: 4000,
	MAX_DIRECTION_CHANGE: 6000,

	// Cloud core appearance constants
	CORE_MIN_ALPHA: 0.4,
	CORE_MAX_ALPHA: 0.8,
	CORE_RADIUS_MIN: 0.8,
	CORE_RADIUS_MAX: 1.4,
	CORE_DISTANCE_MIN: 0.2,
	CORE_DISTANCE_MAX: 0.5,
	OVERLAP_MULTIPLIER: 0.7,
	WRAP_FACTOR: 1.5,
	REENTRY_FACTOR: 0.5,
	PLACEMENT_MAX_ATTEMPTS: 20,

	// Size constants based on device
	MOBILE_CORE_RADIUS_MIN: 150,
	MOBILE_CORE_RADIUS_MAX: 300,
	DESKTOP_CORE_RADIUS_MIN: 350,
	DESKTOP_CORE_RADIUS_MAX: 600,

	// Cloud count and positioning
	AREA_PER_CLOUD: 800000,
	MIN_CLOUD_COUNT: 4,
	MAX_CLOUD_COUNT: 6,
	MIN_CLOUD_CORES: 3,
	MAX_CLOUD_CORES: 6,
	POSITION_MIN_PERCENT: 0.2,
	POSITION_MAX_PERCENT: 0.8,
	MIN_DEPTH: 0.5,
	MAX_DEPTH: 1.5
};
