export const StarConfig = {
	// Movement and animation constants
	VELOCITY_FACTOR: 0.2,
	TARGET_VELOCITY_FACTOR: 0.3,
	EASING_FACTOR: 0.02,
	MOVEMENT_SPEED: 0.1,
	MIN_DIRECTION_CHANGE: 5000,
	MAX_DIRECTION_CHANGE: 10000,

	// Star appearance constants
	SIZE_MIN: 0.3,
	SIZE_MAX: 1.3,
	ALPHA_MIN: 0.5,
	ALPHA_MAX: 1.0,

	// Twinkling effect
	TWINKLE_SPEED_MIN: 0.001,
	TWINKLE_SPEED_MAX: 0.003,
	TWINKLE_MAX_MIN: 0.2,
	TWINKLE_MAX_MAX: 0.5,
	TWINKLE_FACTOR: 0.05,

	// Positioning and count
	EDGE_BUFFER: 20,
	MIN_DEPTH: 0.1,
	MAX_DEPTH: 2.0,
	MOBILE_BASE_STAR_COUNT: 40,
	DESKTOP_STAR_COUNT: 80,
	MOBILE_AREA_PER_STAR: 100000
};
